import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cawine",
  description: "Generated by cawine",
  icons: {
        icon: [
          {
            media: '(prefers-color-scheme: light)',
            url: '/cawine_main_icon_round.png', // Path relative to public directory
          },
          {
            media: '(prefers-color-scheme: dark)',
            url: '/cawine_main_icon_round.png', // Path relative to public directory
          },
        ],
      },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
